### ISSUE TITLE
Running inference on sentences

### ISSUE THREAD

**Issue by PratikGarai** [cgraywang/deepex#14]
Hi,
I am unable to figure out how to use the deepex model. I want to input a sentence and get the triplets generated from it. Is there any code snippet/script in the repo that can help me do that?

Thanks

**Comment by filip-cermak** [comment]
Same, this should be very straightforward to do imho

**Comment by filip-cermak** [comment]
See my issue, where I explain how to do this:
https://github.com/cgraywang/deepex/issues/17

**Comment by PratikGarai** [comment]
I followed similar steps as you did in #17 , but looking at the poor results, I assumed I had executed the steps in a wrong manner. Hence I kept the issue open waiting for responses.

**Comment by jesseliu0913** [comment]
hi! I thought in the config files, they indicate the input file path, you can according to the manager.py file to append or replace the orginal sentence. More, it will have some bias with your expectation due to the model have not attain the 100% auc in every dataset, so adding more data would be more convincing.
